### ISSUE TITLE
Create docs

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#101]
Most of our docs come from the cytoscape.js website and I think it makes sense to a certain point since this is mostly a python implementation of their lib. But I think we have enough differences to create our own.

We can use this: https://packaging.python.org/tutorials/creating-documentation/

**Comment by martinRenou** [comment]
You have a `doc` directory that was generated by the cookie-cutter, it might be just a matter of enabling readthedocs for this repository and starting writing it :)

**Comment by marimeireles** [comment]
Be specific about the types we receive in ids: https://github.com/QuantStack/ipycytoscape/pull/54/files#r448252899

**Comment by marimeireles** [comment]
Document all these diff selectors we can use: https://js.cytoscape.org/#selectors

**Comment by joseberlines** [comment]
Just posting this here since I am looking for examples and documentation in google about ipycytoscape. I think the documentation for a graph library would include the jpegs (or gifs) of the resulting graphs. this is extremely useful for learning. As beginner with ipycytoscape I would suggest to include in the documentation (or also here in github) an approach like the one @martinRenou uses for ipysheets where a bit of code is followed by a jpeg or gif showing the result of the snippet.

**Comment by ianhi** [comment]
I'm feeling inspired and plan on making a first pass a creating docs this weekend. While I think I have the rights to create to enable readthedocs I think it makes more sense for quantstack employee to do that? This is relevant for the initial documentation because it would be great to add https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html to PRs so that everyone can easily comment on it to review. 

I think the most relevant people to enable it are @marimeireles or @SylvainCorlay

**Comment by JohanMabille** [comment]
The project on readthedocs already existsuser:JohanMabille but the build is still failing due to an issue in installing some dependencies fo rbuilding the documentation. THis is why the webhook has not been plugged yet.

However, the skeleton for building the documentation locally is in the repo, so maybe you can start to write the doc and check the rendering locally?

I will make a pass on the documentation settings of all our projects during the next week, I'm adding this one to my todo list.

**Comment by marimeireles** [comment]
That's a really good idea @joseberlines! As Johan said we're having a problem with it

Yeah, not sure if I can grant you permissions @JohanMabille because I was the one who created it, but let me know and I can change that.

We're having this issue right now and I'm investigating it:
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/checkouts/latest
Collecting ipywidgets>=7.0.0
  Downloading ipywidgets-7.5.1-py2.py3-none-any.whl (121 kB)
Collecting spectate>=0.4.1
  Downloading spectate-0.4.1-py3-none-any.whl (24 kB)
Requirement already up-to-date: sphinx>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from ipycytoscape==1.0.3) (3.2.0)
Requirement already up-to-date: recommonmark in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from ipycytoscape==1.0.3) (0.6.0)
Collecting sphinx_rtd_theme
  Downloading sphinx_rtd_theme-0.5.0-py2.py3-none-any.whl (10.8 MB)
Collecting nbsphinx<0.4.0,>=0.2.13
  Downloading nbsphinx-0.3.5-py2.py3-none-any.whl (18 kB)
Collecting jupyter_sphinx
  Downloading jupyter_sphinx-0.2.4-py3-none-any.whl (19 kB)
Collecting nbsphinx-link
  Downloading nbsphinx_link-1.3.0-py2.py3-none-any.whl (5.2 kB)
Collecting pytest_check_links
  Downloading pytest_check_links-4.3.3.tar.gz (13 kB)
Collecting pypandoc
  Downloading pypandoc-1.5.tar.gz (26 kB)
Collecting networkx
  Downloading networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting pandas
  Downloading pandas-0.25.3-cp35-cp35m-manylinux1_x86_64.whl (10.3 MB)
Collecting widgetsnbextension~=3.5.0
  Downloading widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2 MB)
Collecting ipykernel>=4.5.1
  Downloading ipykernel-5.3.4-py3-none-any.whl (120 kB)
Collecting traitlets>=4.3.1
  Downloading traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Requirement already up-to-date: nbformat>=4.2.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from ipywidgets>=7.0.0->ipycytoscape==1.0.3) (5.0.7)
Collecting ipython>=4.0.0; python_version >= "3.3"
  Downloading ipython-7.9.0-py3-none-any.whl (775 kB)
Collecting funcsigs; python_version < "3.6"
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Requirement already up-to-date: sphinxcontrib-devhelp in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.0.2)
Requirement already up-to-date: babel>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (2.8.0)
Requirement already up-to-date: sphinxcontrib-htmlhelp in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.0.3)
Requirement already up-to-date: Jinja2>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (2.11.2)
Requirement already up-to-date: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (2.0.0)
Requirement already up-to-date: alabaster<0.8,>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (0.7.12)
Requirement already up-to-date: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.2.0)
Requirement already up-to-date: requests>=2.5.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (2.24.0)
Collecting setuptools
  Downloading setuptools-49.3.2-py3-none-any.whl (790 kB)
Requirement already up-to-date: packaging in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (20.4)
Requirement already up-to-date: sphinxcontrib-serializinghtml in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.1.4)
Requirement already up-to-date: sphinxcontrib-qthelp in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.0.3)
Requirement already up-to-date: Pygments>=2.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (2.6.1)
Requirement already up-to-date: sphinxcontrib-jsmath in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.0.1)
Requirement already up-to-date: sphinxcontrib-applehelp in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from sphinx>=1.5->ipycytoscape==1.0.3) (1.0.2)
Collecting docutils>=0.12
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
Requirement already up-to-date: commonmark>=0.8.1 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from recommonmark->ipycytoscape==1.0.3) (0.9.1)
Collecting nbconvert!=5.4
  Downloading nbconvert-5.6.1-py2.py3-none-any.whl (455 kB)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting pytest>=4.6
  Downloading pytest-6.0.1-py3-none-any.whl (270 kB)
Requirement already up-to-date: pip>=8.1.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from pypandoc->ipycytoscape==1.0.3) (20.2.2)
Requirement already up-to-date: wheel>=0.25.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from pypandoc->ipycytoscape==1.0.3) (0.34.2)
Requirement already up-to-date: decorator>=4.3.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from networkx->ipycytoscape==1.0.3) (4.4.2)
Requirement already up-to-date: pytz>=2017.2 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from pandas->ipycytoscape==1.0.3) (2020.1)
Collecting numpy>=1.13.3
  Downloading numpy-1.18.5-cp35-cp35m-manylinux1_x86_64.whl (19.9 MB)
Requirement already up-to-date: python-dateutil>=2.6.1 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from pandas->ipycytoscape==1.0.3) (2.8.1)
Collecting notebook>=4.4.1
  Downloading notebook-6.1.3-py3-none-any.whl (9.4 MB)
Collecting tornado>=4.2
  Downloading tornado-6.0.4.tar.gz (496 kB)
Collecting jupyter-client
  Downloading jupyter_client-6.1.6-py3-none-any.whl (108 kB)
Requirement already up-to-date: six in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from traitlets>=4.3.1->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (1.15.0)
Requirement already up-to-date: ipython-genutils in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from traitlets>=4.3.1->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (0.2.0)
Collecting jsonschema!=2.5.0,>=2.4
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting jupyter-core
  Downloading jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Requirement already up-to-date: pickleshare in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (0.7.5)
Collecting jedi>=0.10
  Downloading jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Collecting pexpect; sys_platform != "win32"
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Requirement already up-to-date: backcall in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (0.2.0)
Requirement already up-to-date: prompt-toolkit<2.1.0,>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (2.0.10)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp35-cp35m-manylinux1_x86_64.whl (27 kB)
Requirement already up-to-date: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from requests>=2.5.0->sphinx>=1.5->ipycytoscape==1.0.3) (1.25.10)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Requirement already up-to-date: idna<3,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from requests>=2.5.0->sphinx>=1.5->ipycytoscape==1.0.3) (2.10)
Requirement already up-to-date: chardet<4,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from requests>=2.5.0->sphinx>=1.5->ipycytoscape==1.0.3) (3.0.4)
Requirement already up-to-date: pyparsing>=2.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from packaging->sphinx>=1.5->ipycytoscape==1.0.3) (2.4.7)
Requirement already up-to-date: testpath in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from nbconvert!=5.4->nbsphinx<0.4.0,>=0.2.13->ipycytoscape==1.0.3) (0.4.4)
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Requirement already up-to-date: bleach in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from nbconvert!=5.4->nbsphinx<0.4.0,>=0.2.13->ipycytoscape==1.0.3) (3.1.5)
Requirement already up-to-date: pandocfilters>=1.4.1 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from nbconvert!=5.4->nbsphinx<0.4.0,>=0.2.13->ipycytoscape==1.0.3) (1.4.2)
Requirement already up-to-date: defusedxml in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from nbconvert!=5.4->nbsphinx<0.4.0,>=0.2.13->ipycytoscape==1.0.3) (0.6.0)
Collecting entrypoints>=0.2.2
  Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Requirement already up-to-date: webencodings in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from html5lib->pytest_check_links->ipycytoscape==1.0.3) (0.5.1)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.4.0-py3-none-any.whl (43 kB)
Collecting toml
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting py>=1.8.2
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting pathlib2>=2.2.0; python_version < "3.6"
  Downloading pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting iniconfig
  Downloading iniconfig-1.0.1-py3-none-any.whl (4.2 kB)
Collecting attrs>=17.4.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting terminado>=0.8.3
  Downloading terminado-0.8.3-py2.py3-none-any.whl (33 kB)
Requirement already up-to-date: Send2Trash in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (1.5.0)
Requirement already up-to-date: prometheus-client in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (0.8.0)
Collecting pyzmq>=17
  Downloading pyzmq-19.0.2-cp35-cp35m-manylinux1_x86_64.whl (1.0 MB)
Collecting argon2-cffi
  Downloading argon2_cffi-20.1.0-cp35-abi3-manylinux1_x86_64.whl (97 kB)
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.16.0.tar.gz (108 kB)
Collecting parso<0.8.0,>=0.7.0
  Downloading parso-0.7.1-py2.py3-none-any.whl (109 kB)
Requirement already up-to-date: ptyprocess>=0.5 in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (0.6.0)
Requirement already up-to-date: wcwidth in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (0.2.5)
Collecting zipp>=0.5
  Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting cffi>=1.0.0
  Downloading cffi-1.14.1-cp35-cp35m-manylinux1_x86_64.whl (400 kB)
Requirement already up-to-date: pycparser in /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/latest/lib/python3.5/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->ipycytoscape==1.0.3) (2.20)
Building wheels for collected packages: ipycytoscape, pytest-check-links, pypandoc, tornado, pyrsistent
  Building wheel for ipycytoscape (setup.py): started
  Building wheel for ipycytoscape (setup.py): still running...
  Building wheel for ipycytoscape (setup.py): finished with status 'done'
  Created wheel for ipycytoscape: filename=ipycytoscape-1.0.3-py2.py3-none-any.whl size=2906395 sha256=2d147d1ee453e5e2a0f0a3cd3b249a0d8fd2a654936733f0d9584911ac82a32f
  Stored in directory: /tmp/pip-ephem-wheel-cache-1mw7r7dd/wheels/10/40/25/e69beda742e1e4d519581d149ae83d97f3748b2f771cfea5b1
  Building wheel for pytest-check-links (setup.py): started
  Building wheel for pytest-check-links (setup.py): finished with status 'done'
  Created wheel for pytest-check-links: filename=pytest_check_links-4.3.3-py3-none-any.whl size=9572 sha256=a4722b784f696865105fd8c20d39429732621970ebb790ec96ff31ead6333ef7
  Stored in directory: /tmp/pip-ephem-wheel-cache-1mw7r7dd/wheels/9d/9a/e4/ecfd2c138729d365ddc0b772183e535e248441af04e0789a33
  Building wheel for pypandoc (setup.py): started
  Building wheel for pypandoc (setup.py): finished with status 'done'
  Created wheel for pypandoc: filename=pypandoc-1.5-py3-none-any.whl size=17036 sha256=fdea2cca2c652b29cbe709a29e3e90ad6d2c134c3b936d2d9467a8a09d553c32
  Stored in directory: /tmp/pip-ephem-wheel-cache-1mw7r7dd/wheels/fb/f7/38/f445b936d74dd4c2d176de5f282976510c53d28bf7b96344a6
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-6.0.4-cp35-cp35m-linux_x86_64.whl size=427449 sha256=4e487b6e29bd85f4d0ff016c30bf83fff8b52001863fcd8410dee40a5175c2b4
  Stored in directory: /tmp/pip-ephem-wheel-cache-1mw7r7dd/wheels/68/3c/1e/fd5ff3580fd107e6785d42a2d7e690396d1cefa44813561c29
  Building wheel for pyrsistent (setup.py): started
  Building wheel for pyrsistent (setup.py): finished with status 'done'
  Created wheel for pyrsistent: filename=pyrsistent-0.16.0-cp35-cp35m-linux_x86_64.whl size=115001 sha256=142e8c0546c2f3667f63580a2824c84eda4d52ae623c82f45c824ce5713420d6
  Stored in directory: /tmp/pip-ephem-wheel-cache-1mw7r7dd/wheels/f1/3d/7d/164146cafaba2e9030e2a28c54ed76aa13363cd339fa700687
Successfully built ipycytoscape pytest-check-links pypandoc tornado pyrsistent
Installing collected packages: tornado, terminado, traitlets, jupyter-core, pyzmq, jupyter-client, setuptools, parso, jedi, pexpect, ipython, ipykernel, mistune, entrypoints, nbconvert, cffi, argon2-cffi, notebook, widgetsnbextension, ipywidgets, funcsigs, spectate, sphinx-rtd-theme, docutils, nbsphinx, jupyter-sphinx, nbsphinx-link, html5lib, zipp, importlib-metadata, pluggy, more-itertools, toml, py, pathlib2, iniconfig, attrs, pytest, pytest-check-links, pypandoc, networkx, numpy, pandas, ipycytoscape, pyrsistent, jsonschema, MarkupSafe, certifi
  Attempting uninstall: tornado
    Found existing installation: tornado 5.1.1
    Uninstalling tornado-5.1.1:
      Successfully uninstalled tornado-5.1.1
  Attempting uninstall: terminado
    Found existing installation: terminado 0.8.1
ERROR: Cannot uninstall 'terminado'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

If you wanna contribute to the docs and not build them, you can. You just have to add `.rst` files to the documentation directory. You can check out other documentations like this one to have an idea of how you can build the structure: https://xeus.readthedocs.io/en/latest/ here is the github: https://github.com/jupyter-xeus/xeus

**Comment by JohanMabille** [comment]
I don't think I need any permission on RTD actually, I think we need to fix the config in readthedoc.yml / docs/environment.yml

**Comment by ianhi** [comment]
Ah I see. I meant to suggest two thing originally
1. Enable RTD (done :smile: )
2. Enable autobuild on PRs

With 2. it adds a check to all PRs that will build on RTD so you get confidence about whether it build. Also, if it built successfully, it then allows everyone to view the rendered version pre-merge.
![image](https://user-images.githubusercontent.com/10111092/90402729-dfdbc300-e06d-11ea-84ab-06289b430c15.png)
(sorry about the arrow there, image was from showing someone how to see the build details)

I this to be very helpful for debugging a RTD build on a different project, and think it lowers the barrier to entry for someone to write the doc. So I would be pro adding the PR check as well. If others feel similarly that setting is in Admin > Advanced Settings > Build Pull Requests for Projects
![image](https://user-images.githubusercontent.com/10111092/90402643-bf136d80-e06d-11ea-94b6-3e21fbc4143b.png)

**Comment by marimeireles** [comment]
Oh nice! Thanks @ianhi you're great as always :)
Don't know much about read the docs at all. Just enabled it.

**Comment by marimeireles** [comment]
Ok, so I tried for a while last night. Don't really know what's going on here.
```
Running Sphinx v3.2.1
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/sphinx/registry.py", line 409, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/jupyter_sphinx/embed_widgets.py", line 58, in <module>
    from ipywidgets import Widget
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 33, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/conda/docs/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-41lwsr3u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

I'm getting this error as if I was using an older python version than 3.5 but I'm actually using 3.6.
It works when I build on my computer, but doesn't when I build on rtd. I think I'll open an issue in this sphinx repo.

**Comment by ianhi** [comment]
Maybe this line in readthedocs.yml is messing us up?
https://github.com/QuantStack/ipycytoscape/blob/112d0b207482629e2e0f8f17acac040dece86571/readthedocs.yml#L2

in mpl_interactions I explicitly set it to 3.7 https://github.com/ianhi/mpl-interactions/blob/2d53804acf46bd5b5c245e5e31b0d3b94c0daac2/readthedocs.yml#L3

**Comment by marimeireles** [comment]
Hum! I thought I had changed that one too.
Thanks for the catch! Will try to set this one too.

**Comment by marimeireles** [comment]
Sorry, I did change there, I'm running tests on the `docs` branch because I'm still waiting for Sylvain to activate the hooks necessary to connect rtd with github.

**Comment by marimeireles** [comment]
Oh sweeet https://ipycytoscape.readthedocs.io/en/latest/
We finally have it running again!
@joseberlines please feel free to contribute with what you know, it'll be much appreciated! As I said I'm available to talk if you need anything.

**Comment by joseberlines** [comment]
Hei @marimeireles Wonderfull. I am going this weekend over all the examples. I consider myself a beginner and I will give some feed back, if I consider that the notebooks I create are of use I will sent some to you. My main point here is that a beginner might start at the same beginner position learning about graphs and about plotting them. So for instance something that I considered should be part of the first Jupiter notebook example is including "names" in the nodes. I am building an example from scratch.

**Comment by ianhi** [comment]
@marimeireles which branch should documentation be going into? The master branch or the docs branch?

**Comment by marimeireles** [comment]
Thanks a lot @joseberlines!
@ianhi, you can open a PR to the master. I think the read the docs website should be connected with the ipycytoscape docs, so they should build every time you open a PR now. To build locally to test you can follow this [quick start](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start). Feel free to change whatever you want, whatever is in there is super old and probably doesn't make sense anymore.
Thanks! 🌸

**Comment by ianhi** [comment]
btw @marimeireles I added the readthedocs as the website for the repo so it will show up on the right of the github page
![image](https://user-images.githubusercontent.com/10111092/91681183-97b3aa80-eb1b-11ea-8630-9399d538e384.png)


And how do you feel about changing the description to read something like: 

Interactive graphs visualization in Jupyter Notebooks using cytoscape.js

**Comment by ianhi** [comment]
https://github.com/QuantStack/ipycytoscape/pull/150 should go most of the way to having useful documentation. Some things that the docs will still need:

- [ ] A single, long form, example showcasing the different layouts
- [ ] A monolithic "how to style" tutorial
- [ ] Autogenerated API page
- [ ] General clean up of the examples with more explanations
    - e.g. networkx example is confusing with instructions on how to add multiple graphs as all cells are run before being shown to the user

**Comment by ianhi** [comment]
One more issue. The custom node part of the networkx examples raises an error:
https://ipycytoscape.readthedocs.io/en/latest/examples/networkx.html#Custom-networkx-Node-Objects

bc the example uses functionality on master but that is not in the latest release 1.0.3.

maybe we should have readthedocs install the master branch instead?

Also, maybe a new release?

**Comment by marimeireles** [comment]
> maybe we should have readthedocs install the master branch instead?

I really don't know what's the protocol here. But I'd be fine with that, don't see any immediate problems.

> Also, maybe a new release?

Will do :)

**Comment by ianhi** [comment]
for mpl-interactions I don't use environment.yml and just have read the docs run `pip install .[docs]` and that seems to work pretty well. See here: https://github.com/ianhi/mpl-interactions/blob/master/readthedocs.yml

**Comment by ianhi** [comment]
> Will do :)

:tada: :tada: - I guess it also is worth removing the pinned version in docs/environment.yml otherwise rtd won't pick up the newest change. Or else swapping to the pip strategy for rtd

**Comment by marimeireles** [comment]
> for mpl-interactions I don't use environment.yml and just have read the docs run `pip install .[docs]` and that seems to work pretty well. See here: https://github.com/ianhi/mpl-interactions/blob/master/readthedocs.yml

Yeah, I think there are many different ways of achieving this. Apparently the [recommended way by rtd](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#specifying-a-requirements-file) is using a `requirements.txt` file, I don't really know what's the difference from that to using a yml, but yeah, I'd be up for using the same as mpl-interactions too, if you think it works better. 

>  I guess it also is worth removing the pinned version in docs/environment.yml 

And thanks! Had forgot about that already.

I'm gonna do both then, now.

**Comment by marimeireles** [comment]
Thanks for the input folks.
Hacktoberfest ppl, please see as a reference:
https://github.com/QuantStack/ipycytoscape/issues/101#issuecomment-683535556
https://github.com/QuantStack/ipycytoscape/issues/101#issuecomment-685963206

**Comment by ianhi** [comment]
And there are instructions for how to build the docs locally! See https://ipycytoscape.readthedocs.io/en/latest/contributing.html#documentation

**Comment by marimeireles** [comment]
I'm gonna close this because thanks to @ianhi we have amazing docs now.
I'll create a new issue with more specific goals on what we want to achieve from now on.
